import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/organisms/navigation";
import Footer from "@/components/molecules/footer";

const redHatText = Red_Hat_Text({
  variable: "--font-red_hat_text",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${redHatText.variable} antialiased`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
